# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateCharacterForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1085, 296)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

        self.classCBox = QtWidgets.QComboBox(Form)
        self.classCBox.setGeometry(QtCore.QRect(700, 25, 210, 30))
        self.classCBox.setObjectName("classCBox")
        self.classCBox.addItem("")
        self.classCBox.addItem("")
        self.classCBox.addItem("")
        self.classCBox.addItem("")
        self.classCBox.addItem("")
        self.classCBox.addItem("")
        self.classCBox.addItem("")
        self.classCBox.addItem("")

        self.nameEdit = QtWidgets.QTextEdit(Form)
        self.nameEdit.setGeometry(QtCore.QRect(100, 25, 210, 30))
        self.nameEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.nameEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.nameEdit.setObjectName("nameEdit")
        
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(640, 30, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.speciesCBox = QtWidgets.QComboBox(Form)
        self.speciesCBox.setGeometry(QtCore.QRect(400, 25, 210, 30))
        self.speciesCBox.setEditable(False)
        self.speciesCBox.setFrame(True)
        self.speciesCBox.setObjectName("speciesCBox")
        self.speciesCBox.addItem("")
        self.speciesCBox.addItem("")
        self.speciesCBox.addItem("")
        self.speciesCBox.addItem("")
        self.speciesCBox.addItem("")
        self.speciesCBox.addItem("")

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(330, 30, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        
        self.levelSBox = QtWidgets.QSpinBox(Form)
        self.levelSBox.setGeometry(QtCore.QRect(990, 25, 61, 30))
        self.levelSBox.setAlignment(QtCore.Qt.AlignCenter)
        self.levelSBox.setSuffix("")
        self.levelSBox.setMinimum(1)
        self.levelSBox.setMaximum(20)
        self.levelSBox.setObjectName("levelSBox")
        
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(930, 30, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(430, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        self.ConfirmButton = QtWidgets.QPushButton(Form)
        self.ConfirmButton.setGeometry(QtCore.QRect(400, 240, 91, 31))
        self.ConfirmButton.setObjectName("ConfirmButton")
        
        self.CancelButton = QtWidgets.QPushButton(Form)
        self.CancelButton.setGeometry(QtCore.QRect(510, 240, 101, 31))
        self.CancelButton.setObjectName("CancelButton")
        
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 130, 1041, 51))
        self.widget.setObjectName("widget")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        
        self.STRsBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.STRsBox.setGeometry(QtCore.QRect(1, 20, 81, 22))
        self.STRsBox.setMinimum(1)
        self.STRsBox.setMaximum(20)
        self.STRsBox.setProperty("value", 10)
        self.STRsBox.setObjectName("STRsBox")
        self.horizontalLayout.addWidget(self.groupBox_2)
        
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.DEXsBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.DEXsBox.setGeometry(QtCore.QRect(1, 20, 81, 22))
        self.DEXsBox.setMinimum(1)
        self.DEXsBox.setMaximum(20)
        self.DEXsBox.setProperty("value", 10)
        self.DEXsBox.setObjectName("DEXsBox")
        self.horizontalLayout.addWidget(self.groupBox_3)
        
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.CONsBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.CONsBox.setGeometry(QtCore.QRect(1, 20, 81, 22))
        self.CONsBox.setMinimum(1)
        self.CONsBox.setMaximum(20)
        self.CONsBox.setProperty("value", 10)
        self.CONsBox.setObjectName("CONsBox")
        self.horizontalLayout.addWidget(self.groupBox_4)
        
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.INTsBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.INTsBox.setGeometry(QtCore.QRect(1, 20, 81, 22))
        self.INTsBox.setMinimum(1)
        self.INTsBox.setMaximum(20)
        self.INTsBox.setProperty("value", 10)
        self.INTsBox.setObjectName("INTsBox")
        self.horizontalLayout.addWidget(self.groupBox_7)
        
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.WISsBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.WISsBox.setGeometry(QtCore.QRect(1, 20, 81, 22))
        self.WISsBox.setMinimum(1)
        self.WISsBox.setMaximum(20)
        self.WISsBox.setProperty("value", 10)
        self.WISsBox.setObjectName("WISsBox")
        self.horizontalLayout.addWidget(self.groupBox_8)
        
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.CHAsBox = QtWidgets.QSpinBox(self.groupBox_9)
        self.CHAsBox.setGeometry(QtCore.QRect(1, 20, 81, 22))
        self.CHAsBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CHAsBox.setMinimum(1)
        self.CHAsBox.setMaximum(20)
        self.CHAsBox.setProperty("value", 10)
        self.CHAsBox.setObjectName("CHAsBox")
        self.horizontalLayout.addWidget(self.groupBox_9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

        self.classCBox.setItemText(0, _translate("Form", "Choose a Class"))
        self.classCBox.setItemText(1, _translate("Form", "Druid"))
        self.classCBox.setItemText(2, _translate("Form", "Paladin"))
        self.classCBox.setItemText(3, _translate("Form", "Fighter"))
        self.classCBox.setItemText(4, _translate("Form", "Ranger"))
        self.classCBox.setItemText(5, _translate("Form", "Warlock"))
        self.classCBox.setItemText(6, _translate("Form", "Wizzard"))
        self.classCBox.setItemText(7, _translate("Form", "Barbarian"))

        self.nameEdit.setPlaceholderText(_translate("Form", "Insert name here"))

        self.label.setText(_translate("Form", "Name:"))
        self.label_2.setText(_translate("Form", "Class:"))

        self.speciesCBox.setItemText(0, _translate("Form", "Choose a Species"))
        self.speciesCBox.setItemText(1, _translate("Form", "Elf"))
        self.speciesCBox.setItemText(2, _translate("Form", "Human"))
        self.speciesCBox.setItemText(3, _translate("Form", "Dwarf"))
        self.speciesCBox.setItemText(4, _translate("Form", "Half Elf"))
        self.speciesCBox.setItemText(5, _translate("Form", "Gnome"))

        self.label_3.setText(_translate("Form", "Species:"))
        self.label_4.setText(_translate("Form", "Level:"))
        self.label_5.setText(_translate("Form", "Ability Scores:"))
        
        self.ConfirmButton.setText(_translate("Form", "Confirm"))
        self.CancelButton.setText(_translate("Form", "Cancel"))

        self.groupBox_2.setTitle(_translate("Form", "Strenght:"))
        self.groupBox_3.setTitle(_translate("Form", "Dexterity:"))
        self.groupBox_4.setTitle(_translate("Form", "Constitution:"))
        self.groupBox_7.setTitle(_translate("Form", "Intelligence:"))
        self.groupBox_8.setTitle(_translate("Form", "Wisdom:"))
        self.groupBox_9.setTitle(_translate("Form", "Charisma"))
