# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

LOGO_PATH = r'C:\Users\user\Desktop\my stuff\CharDnD\Frontend\resources\iron_man_logo.png'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.setWindowTitle("Adventure Companion")
        self.setWindowIcon(QtGui.QIcon(LOGO_PATH))
        self.resize(1085, 296)

        self.newCharacterButton = QtWidgets.QPushButton("New Character", MainWindow)
        self.newCharacterButton.setGeometry(QtCore.QRect(150, 130, 360, 50))
        self.newCharacterButton.setObjectName("NewCharacter")

        self.loadCharacterButton = QtWidgets.QPushButton("Load Character", MainWindow)
        self.loadCharacterButton.setGeometry(QtCore.QRect(150, 180, 360, 50))
        self.loadCharacterButton.setObjectName("LoadCharacter")
        
        self.toolButton = QtWidgets.QToolButton(MainWindow)
        self.toolButton.setGeometry(QtCore.QRect(600, 330, 51, 41))
        self.toolButton.setText("Tools")
        self.toolButton.setObjectName("toolButton")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
